import React, { useEffect, useState } from 'react';

export default function ViewInvoices() {
  const [invoices, setInvoices] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    fetchInvoices();
  }, []);

  const fetchInvoices = async () => {
    try {
      const response = await fetch('http://localhost:5209/api/invoice');
      if (response.ok) {
        const data = await response.json();
        setInvoices(data);
      } else {
        setError('Failed to load invoices.');
      }
    } catch (err) {
      setError('Error connecting to the server.');
    } finally {
      setLoading(false);
    }
  };

  if (loading) return <p style={{ textAlign: 'center', padding: '50px' }}>Loading history...</p>;
  if (error) return <p style={{ color: '#ef4444', textAlign: 'center', padding: '50px' }}>{error}</p>;

  return (
    <div className="route-card">
      <span className="route-eyebrow">Financial Records</span>
      <h1 className="route-title">Invoice History</h1>
      <p className="route-copy" style={{ marginBottom: '32px' }}>
        View all purchase and sales invoices generated by the system.
      </p>

      <div style={{ overflowX: 'auto' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', minWidth: '600px' }}>
          <thead>
            <tr style={{ borderBottom: '2px solid #e2e8f0', textAlign: 'left' }}>
              <th style={{ padding: '12px 16px' }}>Date</th>
              <th style={{ padding: '12px 16px' }}>Type</th>
              <th style={{ padding: '12px 16px' }}>Total Amount</th>
              <th style={{ padding: '12px 16px' }}>Status</th>
              <th style={{ padding: '12px 16px' }}>Items</th>
            </tr>
          </thead>
          <tbody>
            {invoices.map((inv) => (
              <tr key={inv.id} style={{ borderBottom: '1px solid #f1f5f9', transition: 'background-color 150ms' }} className="table-row-hover">
                <td style={{ padding: '16px' }}>{new Date(inv.invoiceDate).toLocaleDateString()}</td>
                <td style={{ padding: '16px' }}>
                  <span style={{ 
                    padding: '4px 10px', 
                    borderRadius: '999px', 
                    fontSize: '0.8rem', 
                    fontWeight: 700,
                    background: inv.type === 'Purchase' ? '#dcfce7' : '#dbeafe',
                    color: inv.type === 'Purchase' ? '#166534' : '#1e40af'
                  }}>
                    {inv.type}
                  </span>
                </td>
                <td style={{ padding: '16px', fontWeight: 600 }}>${inv.totalAmount.toFixed(2)}</td>
                <td style={{ padding: '16px' }}>
                  <span style={{ 
                    color: inv.paymentStatus === 'Paid' ? '#10b981' : '#f59e0b',
                    fontWeight: 600
                  }}>
                    {inv.paymentStatus}
                  </span>
                </td>
                <td style={{ padding: '16px' }}>
                    {inv.invoiceItems?.length || 0} items
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        {invoices.length === 0 && (
          <p style={{ textAlign: 'center', padding: '40px', color: '#64748b' }}>No invoices found.</p>
        )}
      </div>
      
      <style>{`
        .table-row-hover:hover {
            background-color: #f8fafc;
        }
      `}</style>
    </div>
  );
}
